[package]
name = "test_sm"
version = "0.1.0"
edition = "2021"

[dependencies]
identity_iota = { version = "0.6" }
iota-client = { version = "2.0.1-rc.4", default-features = false, features = ["tls", "stronghold"] }
tokio = { version = "1", features = ["full"] }