name: did_append_contract
description: did_append_contract description
author: Ilias El Abbassi <iliaselabbassi@outlook.fr>
events: {}
structs: {}
typedefs: {}
state:
  owner: AgentID // current owner of this smart contract
  DID: String[]
funcs:
  init:
    params:
      owner: AgentID? // optional owner of this smart contract
  setOwner:
    access: owner // current owner of this smart contract
    params:
      owner: AgentID // new owner of this smart contract
  addDid:
    params:
      newDID: String
  deleteDid:
    params:
      toDeleteDID: String
  updateDid:
    params:
      toUpdateDID: String
      value: String
views:
  getLength:
    results:
      length: Uint8
  getDID:
    params:
      index: Uint8
    results:
      indexedDID: String
  getOwner:
    results:
      owner: AgentID // current owner of this smart contract